### ISSUE TITLE
Master nodes get wrong label

### ISSUE THREAD

**Issue by dverbeek84** [openshift/cluster-control-plane-machine-set-operator#265]
Hi,

I am testing out this operator on our cluster but it fails to finish on our vmware plaform because the nodes joins the cluster a worker.
By manual changing the labels to master and control-plane is works.

This is our config:

```
apiVersion: machine.openshift.io/v1
kind: ControlPlaneMachineSet
metadata:
  name: cluster
  namespace: openshift-machine-api
spec:
  replicas: 3
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: cl01-f7p2m
      machine.openshift.io/cluster-api-machine-role: master
      machine.openshift.io/cluster-api-machine-type: master
  state: Active
  strategy:
    type: RollingUpdate
  template:
    machineType: machines_v1beta1_machine_openshift_io
    machines_v1beta1_machine_openshift_io:
      metadata:
        labels:
          machine.openshift.io/cluster-api-cluster: cl01-f7p2m
          machine.openshift.io/cluster-api-machine-role: master
          machine.openshift.io/cluster-api-machine-type: master
      spec:
        metadata:
          labels:

        providerSpec:
          value:
            numCoresPerSocket: 4
            diskGiB: 240
            snapshot: ''
            userDataSecret:
              name: worker-user-data
            memoryMiB: 32768
            credentialsSecret:
              name: vsphere-cloud-credentials
            metadata: { }
            numCPUs: 4
            kind: VSphereMachineProviderSpec
            network:
              devices:
                - networkName: xxx
                - networkName: xxx
            workspace:
              datacenter: ITS
              folder: /ITS/vm/OpenShift/
              datastore: xxxx
              resourcePool: xxxx
              server: xxxx
            template: /ITS/vm/OpenShift/templates/openshift-4.14.1
            apiVersion: machine.openshift.io/v1beta1
```

and this is the lables set on the node

` cl01-f7p2m-master-gpgvk-0                 Ready                 worker`

**Comment by dverbeek84** [comment]
adding this to the spec.template.spec fix the issue, but is this also they way to go? because this is not documented.

https://docs.openshift.com/container-platform/4.14/machine_management/control_plane_machine_management/cpmso-configuration.html#cpmso-yaml-sample-cr_cpmso-configuration

```
spec:
  ... 
  template:
     ...
      spec:
        metadata:
          labels:
            node-role.kubernetes.io/control-plane: ""
            node-role.kubernetes.io/master: "" 
```
